# Shark Tank Continued

## Due Tuesday, April 19 at 8:00 AM
(Note the extra time for this assignment.)

In [1]:
import pandas as pd
data = pd.read_csv("/data/sharktank.csv")

Calculate the percentage of companies that were funded, sliced by industry. Do the sharks seem to favor or dislike any particular industries?

In [2]:
invested = data.groupby("Industry")['Amount'].count()
total = data.fillna(0).groupby("Industry")['Amount'].count()
invested
total
percent_invested = invested/total
newdataframe = percent_invested.to_frame()
newdataframe

                         Amount
Industry
Business Services      0.230769
Children / Education   0.527273
Consumer Products      0.526316
Fashion / Beauty       0.462366
Fitness / Sports       0.575000
Food and Beverage      0.538462
Green/CleanTech        0.555556
Healthcare             0.555556
Lifestyle / Home       0.528571
Media / Entertainment  0.545455
Pet Products           0.411765
Software / Tech        0.454545
Uncertain / Other      0.384615

Certain industry's are infact invested in less, most notable is Buisness services. The business services industry only had roughly 23 % of their businesses invested in. This is 15% less than the next lowest invested in industry of Uncertain/other. The remaining industries all have between a ~40 - ~60% chance of being invested in.

Calculate the number of funded companies and the number of total companies, sliced by industry and gender. To make it a bit easier to compare numbers for men and women, let's pivot gender from rows to columns, so that we can see the percentages for men and women side-by-side. Store this pivoted table in a variable; you'll need it for the next part.

In [3]:
funded = data.groupby(['Industry', 'Entrepreneur Gender'])['Amount'].count().reset_index()
funded = funded.pivot_table(index = 'Industry', columns = 'Entrepreneur Gender')
funded
total = data.fillna(0).groupby(['Industry', 'Entrepreneur Gender'])['Amount'].count().reset_index()
total = total.pivot_table(index = 'Industry', columns = 'Entrepreneur Gender')
total
perc = funded / total
perc.fillna("None in group") ## the NaN's mean group had no people in it

                              Amount
Entrepreneur Gender           Female      Male     Mixed Team
Industry
Business Services                  0  0.222222            0.5
Children / Education             0.7  0.409091       0.461538
Consumer Products                  1  0.461538            0.6
Fashion / Beauty            0.486486  0.463415            0.4
Fitness / Sports            0.571429  0.620690           0.25
Food and Beverage           0.535714  0.508475       0.647059
Green/CleanTech        None in group  0.625000              0
Healthcare                  0.333333  0.636364              1
Lifestyle / Home                 0.5  0.480000          0.875
Media / Entertainment              1  0.444444  None in group
Pet Products                     0.8  0.142857            0.4
Software / Tech                 0.25  0.480000            0.5
Uncertain / Other                  0  0.416667  None in group

Use your table to compute 95% confidence intervals for the difference between the percentage of funded companies for men and women, one interval for each industry. Are there any industries where the difference is especially stark and statistically significant?

**HINT**: If it's been a while since your last statistics course, you are looking for a confidence interval for the difference of two proportions. Make sure you used the "pooled" estimate in calculating the standard error.

In [15]:
import math
from scipy.stats import norm
diff = perc.Amount.Male - perc.Amount.Female
z = norm.ppf(.975)
perc.fillna(0)
first = perc.Amount.Male * ( 1- perc.Amount.Male)
first = first / total.Amount.Male.count()
second  = perc.Amount.Female * (1 - perc.Amount.Female)
second = second / total.Amount.Female.count()
sesqr = first + second
se = sesqr**(.5)
lower = diff - (z * se)
upper = diff + (z * se)
perc['lower'] = lower
perc["upper"] = upper
perc

                         Amount                          lower     upper
Entrepreneur Gender      Female      Male Mixed Team
Industry
Business Services      0.000000  0.222222   0.500000 -0.003772  0.448217
Children / Education   0.700000  0.409091   0.461538 -0.663277  0.081458
Consumer Products      1.000000  0.461538   0.600000 -0.809454 -0.267469
Fashion / Beauty       0.486486  0.463415   0.400000 -0.414800  0.368656
Fitness / Sports       0.571429  0.620690   0.250000 -0.335404  0.433926
Food and Beverage      0.535714  0.508475   0.647059 -0.418999  0.364519
Green/CleanTech             NaN  0.625000   0.000000       NaN       NaN
Healthcare             0.333333  0.636364   1.000000 -0.070490  0.676551
Lifestyle / Home       0.500000  0.480000   0.875000 -0.412156  0.372156
Media / Entertainment  1.000000  0.444444        NaN -0.825671 -0.285440
Pet Products           0.800000  0.142857   0.400000 -0.952782 -0.361503
Software / Tech        0.250000  0.480000   0.500000 -0.135758  0.595758
Uncertain / Other      0.000000  0.416667        NaN  0.148670  0.684663

For Uncerain / other the interval is entirely above zero, thus we have statistically significant evidence that entreprenuers within this group that are males( i did males - females) have higer chance of being funded than females.